//
// @file MB.h
// @author Joachim LeBlanc
// @date Jun 05 2012
// @copyright
//   2012 Joachim LeBlanc <demosdemon@gmail.com> \n
//   This program is made available under the terms of the MIT License.
//
// @brief Entry point to the api, import this file and nothing else.

#import <Foundation/Foundation.h>
#import "XML.h"
#import "MBConnection.h"
#import "MBRequest.h"
#import "MBGetRequest.h"
#import "MBPostRequest.h"
#import "MBBarcodeSubmissionRequest.h"
#import "MBIsrcSubmissionRequest.h"
#import "MBPuidSubmissionRequest.h"
#import "MBTagSubmissionRequest.h"
#import "MBRatingSubmissionRequest.h"
#import "MBDeleteRequest.h"
#import "MBPutRequest.h"
#import "MBUtils.h"
#import "MBUniqueIdentifier.h"
#import "NSString+MBKeyManipulation.h"
#import "MBAlias.h"
#import "MBAnnotation.h"
#import "MBArtist.h"
#import "MBArtistCredit.h"
#import "MBAttribute.h"
#import "MBCdstub.h"
#import "MBCollection.h"
#import "MBDisc.h"
#import "MBEntity.h"
#import "MBError.h"
#import "MBFreedbDisc.h"
#import "MBIpi.h"
#import "MBIsrc.h"
#import "MBIswc.h"
#import "MBLabel.h"
#import "MBLabelInfo.h"
#import "MBLifeSpan.h"
#import "MBList.h"
#import "MBMedium.h"
#import "MBMessage.h"
#import "MBMetadata.h"
#import "MBNameCredit.h"
#import "MBNonmbTrack.h"
#import "MBPuid.h"
#import "MBRateAndTaggableEntity.h"
#import "MBRating.h"
#import "MBRecording.h"
#import "MBRelation.h"
#import "MBRelease.h"
#import "MBReleaseGroup.h"
#import "MBTag.h"
#import "MBTextRepresentation.h"
#import "MBTrack.h"
#import "MBUserRating.h"
#import "MBUserTag.h"
#import "MBWork.h"
