#!/usr/bin/python

## @file MBGeneratedDefines.py
## @date Jul 30 2012
## @copyright
##   2012 Brandon LeBlanc <demosdemon@gmail.com>
##   This program is made avaliable under the terms of the MIT License.
##
## @brief Generated MBGeneratedDefines at build time.

import sys
import os
import os.path
import subprocess
import time
import json

def git_sha():
  return subprocess.check_output(['git','rev-parse','--verify','master','--short']).strip()

def def_header():
  maxlen = max([len(key) for key in os.environ])
  DEFINE = u'#define %%-%ds @%%s' % maxlen
  env = [DEFINE % (key.replace('/','_'), json.dumps(val)) for (key, val) in sorted(os.environ.iteritems()) if key != '_']
  
  HEADER = u"""//
// @file MBGeneratedDefines.h
// @author Joachim LeBlanc
// @date %(MB_BUILDTIME_STRING)s
// @copyright
//   2012 Joachim LeBlanc <demosdemon@gmail.com> 
//   This program is made available under the terms of the MIT License.
//
// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY GENERATED BY XCODE DURING BUILD
// ANY CHANGES TO THIS FILE WILL BE ERASED AT NEXT BUILD

""" % os.environ
  
  return HEADER + '\n'.join(env)

def setup_environment():
  os.environ['GIT_WORK_TREE'] = os.getenv('PROJECT_DIR', '.')
  os.environ['GIT_DIR'] = os.getenv('GIT_WORK_TREE') + '/.git'
  os.environ['MB_VERSION'] = git_sha()
  os.environ['MB_BUILDTIME_STRING'] = time.ctime()
  os.environ['MB_BUILDTIME'] = str(int(time.time()))

def main(prog, args):
  setup_environment()
  header_file = os.getenv('PROJECT_DIR', '.') + '/libmusicbrainz-objc/MBGeneratedDefines.h'
  with open(header_file, 'w') as fp:
    fp.write(def_header())

  return 0

if __name__ == '__main__':
  sys.exit(main(
    os.path.abspath(sys.argv[0]),
    sys.argv[1:])
  )